# Generated by Django 4.0.4 on 2022-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_proveedores_productos_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
