# Generated by Django 4.0.4 on 2022-06-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('notificaciones', '0002_alter_notificaciones_vacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.citas'),
        ),
    ]
