# Generated by Django 4.0.4 on 2022-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificaciones_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
