# Generated by Django 4.0.4 on 2022-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_alter_notificaciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='fecha',
            field=models.DateField(),
        ),
    ]
