# Generated by Django 4.0.4 on 2022-05-31 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HistoriasClinicas', '0009_alter_historiasclinicas_inspeccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('dosis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dosisVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_aplicada', models.IntegerField()),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.mascotas')),
                ('vacuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.vacunas')),
            ],
        ),
    ]
