# Generated by Django 4.0.4 on 2022-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_dosisvacunas_fecha_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosisvacunas',
            name='fecha_sgt_dosis',
            field=models.DateField(null=True),
        ),
    ]
