# Generated by Django 4.0.4 on 2022-06-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HistoriasClinicas', '0012_alter_mascotas_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodeCita', models.CharField(choices=[('Consulta', 'Consulta'), ('Control', 'Control')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.mascotas')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tipocita')),
            ],
        ),
    ]
