# Generated by Django 4.0.4 on 2022-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_citas_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='asistencia',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
