# Generated by Django 4.0.4 on 2022-04-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefonos', models.CharField(max_length=45)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pronosticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronostico', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefonos', models.CharField(max_length=45)),
                ('documentoid', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.especies')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.propietarios')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.razas')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.sexos')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriasClinicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('quejaPrincipal', models.CharField(max_length=100)),
                ('tratamientosPrevios', models.CharField(max_length=100)),
                ('enfermedadesAnteriores', models.CharField(max_length=100)),
                ('cirugiasAnteriores', models.CharField(max_length=100)),
                ('dieta', models.CharField(max_length=45)),
                ('medicinaPreventiva', models.CharField(max_length=45)),
                ('temperatura', models.IntegerField()),
                ('pulso', models.IntegerField()),
                ('respiracion', models.IntegerField()),
                ('inspeccion', models.IntegerField()),
                ('TLIC', models.IntegerField()),
                ('hidratacion', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('ganglios', models.CharField(max_length=45)),
                ('sistDigestivo', models.CharField(help_text='(Gusto)', max_length=45)),
                ('sistRespiratorio', models.CharField(help_text='(Olfato)', max_length=45)),
                ('sistCardiovascular', models.CharField(max_length=45)),
                ('sistUrinario', models.CharField(max_length=45)),
                ('sistGenital', models.CharField(max_length=45)),
                ('sistNervioso', models.CharField(help_text='(Visión - Audición)', max_length=45)),
                ('sistLocomotor', models.CharField(max_length=45)),
                ('pielAnexos', models.CharField(max_length=45)),
                ('hallazgos', models.CharField(max_length=200)),
                ('examenesSolicitados', models.CharField(max_length=100)),
                ('examenesAutorizados', models.CharField(max_length=100)),
                ('impresionDiagnostica', models.CharField(max_length=100)),
                ('tratamientoIdeal', models.CharField(max_length=200)),
                ('cotizacion1', models.IntegerField()),
                ('tratamientoInstaurado', models.CharField(max_length=200)),
                ('cotizacion2', models.IntegerField()),
                ('observaciones', models.CharField(max_length=200)),
                ('mascotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.mascotas')),
                ('pronostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.pronosticos')),
                ('veterinario', models.ManyToManyField(to='HistoriasClinicas.empleados')),
            ],
        ),
    ]
