# Generated by Django 4.0.4 on 2022-04-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='nombre',
            new_name='nombreEmp',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='nombre',
            new_name='nombreMas',
        ),
        migrations.RenameField(
            model_name='propietarios',
            old_name='nombre',
            new_name='nombrePr',
        ),
    ]
