# Generated by Django 4.0.4 on 2022-04-26 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HistoriasClinicas', '0002_rename_nombre_empleados_nombreemp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='nombreEmp',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='telefonos',
        ),
        migrations.AddField(
            model_name='empleados',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
