# Generated by Django 4.0.4 on 2022-04-27 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0004_alter_historiasclinicas_tlic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiasclinicas',
            name='TLIC',
            field=models.FloatField(help_text='(seg)'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='hidratacion',
            field=models.FloatField(help_text='(seg)'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='inspeccion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='peso',
            field=models.FloatField(help_text='(Kg)'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='pulso',
            field=models.FloatField(help_text='(X minuto)'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='respiracion',
            field=models.FloatField(help_text='(X minuto)'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='temperatura',
            field=models.FloatField(help_text='(°C)'),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=100)),
                ('historiaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.historiasclinicas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.empleados')),
            ],
        ),
    ]
