# Generated by Django 4.0.4 on 2022-04-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0005_alter_historiasclinicas_tlic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiasclinicas',
            name='pronostico',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Pronosticos',
        ),
    ]
