# Generated by Django 4.0.4 on 2022-05-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0006_alter_historiasclinicas_pronostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='edad',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
