# Generated by Django 4.0.4 on 2022-05-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0007_mascotas_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='caracteristicas',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
