# Generated by Django 4.0.4 on 2022-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0012_alter_mascotas_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietarios',
            name='correo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
