# Generated by Django 4.0.4 on 2022-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0013_alter_propietarios_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiasclinicas',
            name='cirugiasAnteriores',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='dieta',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='enfermedadesAnteriores',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='examenesAutorizados',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='ganglios',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='hallazgos',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='impresionDiagnostica',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='inspeccion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='medicinaPreventiva',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='observaciones',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='pielAnexos',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='pronostico',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='quejaPrincipal',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='sistCardiovascular',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='sistDigestivo',
            field=models.CharField(help_text='(Gusto)', max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='sistGenital',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='sistLocomotor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='sistNervioso',
            field=models.CharField(help_text='(Visión - Audición)', max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='sistRespiratorio',
            field=models.CharField(help_text='(Olfato)', max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='sistUrinario',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='tratamientoIdeal',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='tratamientoInstaurado',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='tratamientosPrevios',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='nombrePr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='telefonos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones',
            field=models.CharField(max_length=250),
        ),
    ]
