# Generated by Django 4.0.4 on 2022-10-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0014_alter_historiasclinicas_cirugiasanteriores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='documentosAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('documentoAD', models.FileField(blank=True, null=True, upload_to='')),
                ('historiaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriasClinicas.historiasclinicas')),
            ],
        ),
    ]
