# Generated by Django 4.0.4 on 2023-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0015_alter_seguimiento_observaciones_documentosad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiasclinicas',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
