# Generated by Django 4.0.4 on 2023-12-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriasClinicas', '0017_alter_historiasclinicas_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiasclinicas',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='hidratacion',
            field=models.FloatField(help_text='(%)'),
        ),
    ]
